### ISSUE TITLE
pubsub client is accessing pubsub-experimental

### ISSUE THREAD

**Issue by canausa** [GoogleCloudPlatform/gcloud-java#1151] opened 2016-08-10 23:20 UTC
This[1] line in the code is bad as the experimental endpoint is not currently available.

https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/gcloud-java-pubsub/src/main/java/com/google/cloud/pubsub/spi/v1/PublisherSettings.java#L112

**Comment by mziccard** [comment] 2016-08-11 07:46
This is a duplicate of https://github.com/GoogleCloudPlatform/gcloud-java/issues/1150. Issue was fixed in https://github.com/GoogleCloudPlatform/gcloud-java/pull/1149. Version `0.2.7-SNAPSHOT` in the snapshot repository contains the fix. `gcloud-java 0.2.7` will be released soon.

**Closed by mziccard** 2016-08-11 07:46 UTC
Labels: pubsub

**Comment by mziccard** [comment] 2016-08-11 14:03
@canausa thanks again for the report. `gcloud-java 0.2.7` is now out and fixes this issue.
