### ISSUE TITLE
Optimize and minimize the library dependencies

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/gcloud-java#71] opened 2015-05-19 02:53 UTC
I see we depend on a lot of transitive libs like JDO/Servlet 2.5 and others. 
A quick test allows me to run all the tests with for example these exclusions:
  <dependency>
      <groupId>com.google.api-client</groupId>
      <artifactId>google-api-client-appengine</artifactId>
      <version>1.20.0</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <artifactId>guava-jdk5</artifactId>
          <groupId>com.google.guava</groupId>
        </exclusion>
        <exclusion>
          <groupId>javax.servlet</groupId>
          <artifactId>servlet-api</artifactId>
        </exclusion>
        <exclusion>
          <groupId>javax.jdo</groupId>
          <artifactId>jdo2-api</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.google.api-client</groupId>
          <artifactId>google-api-client-servlet</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.google.http-client</groupId>
          <artifactId>google-http-client-jdo</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

This one:google-api-client-appengine  (and other) dep might have to be optimized at the source level i.e https://github.com/google/google-api-java-client/tree/dev/google-api-client-appengine
(Main developer is Daniel Wang in CL2...)

**Comment by ludoch** [comment] 2015-05-19 02:53
Above are pom.xml exclusions list

**Comment by aozarov** [comment] 2015-06-01 18:51
I don't think that this issue should be a blocker for [Needed for public announcement](https://github.com/GoogleCloudPlatform/gcloud-java/milestones/Needed%20for%20public%20announcement).

Actually, I am not even sure what to do with it. This issue is mostly about the undesired libraries that the apiary client brings along (and not about direct dependencies by gcloud-java). Until all services switched to gRPC we need this apiary client. I communicated the issue (with suggestion) to the apiary team and they may do something about it but this is not a priority for them.

@jgeewax do you still think this should be a blocker?

**Comment by jgeewax** [comment] 2015-06-02 20:03
Yes it's not clear to me what the problem is... Are we saying "there are a lot of unnecessary dependencies" or "there are a lot of (necessary) dependencies" ? If the former, I think the goal of the issue would be to trim those down, and would agree this belongs as a "get this wrapped up before we make an announcement".

**Comment by aozarov** [comment] 2015-06-02 20:09
We need com.google.api-client and aparently com.google.api-client needs the others mentioned.
@ludoch mentioned (and I agree with him) that apiclient could do better. I indicated that to them but I don't think we can do much more than that at this stage. @ludoch opinion?

**Comment by jgeewax** [comment] 2015-06-02 20:10
I still don't understand. Is it..

1. "there are a lot of unnecessary dependencies" and we need to fix it?, or
1. "there are a lot of (necessary) dependencies" and we're sad about it ?

**Comment by aozarov** [comment] 2015-06-02 20:13
At the moment All dependencies are needed to compile the code. apiclient can do better in various ways. e.g. use reflection in some cases (such as AE dependencies) and use "provided" scope in others (such as J2EE).

**Comment by jgeewax** [comment] 2015-06-02 20:26
So this isn't anything we can do inside *this* repository, correct?

**Comment by aozarov** [comment] 2015-06-02 20:29
Right.

**Comment by jgeewax** [comment] 2015-06-02 20:31
Then I'm closing this out... We should file a bug with someone who can actually do something about the problem.

Thanks all.

**Closed by jgeewax** 2015-06-02 20:31 UTC
