### ISSUE TITLE
Storage insufficient data written

### ISSUE THREAD

**Issue by fonzy2013** [GoogleCloudPlatform/gcloud-java#1018] opened 2016-05-20 15:26 UTC
Could someone help with pointing me to the right direction wrt to an exception I get (sometimes): com.google.cloud.storage.StorageException: insufficient data written.

The code that uploads and fails sometimes is:
````
public void storeInputStream(InputStream input, String fileName, String contentType)
      throws IOException {

    Storage storage = getStorage();

    BlobId blobId = BlobId.of(this.bucketName, fileName);
    LOG.debug("blobId: {}", blobId.toString());
    BlobInfo blobInfo = BlobInfo.builder(blobId).contentType(contentType).build();
    LOG.debug("blobInfo: {}", blobInfo);
    //perform stream uploads of the InputStream
    try (WriteChannel writer = storage.writer(blobInfo)) {
      byte[] buffer = new byte[1024];
      int limit;
      while ((limit = input.read(buffer)) >= 0) {
        writer.write(ByteBuffer.wrap(buffer, 0, limit));
      }
    }
  }
```

**Comment by mziccard** [comment] 2016-05-20 17:33
Hi @fonzy2013, thanks for the report. Could you please share the full stacktrace of the exception?

Also, sharing one sample input streams that causes the exception would really help us figuring out what's going wrong.

**Comment by fonzy2013** [comment] 2016-05-23 07:24
Hi @mziccard ,
unfortunatly I haven't gotten around to reproduce it with files that can be shared but here is the stack trace.
I have a lead and that is that that another instance is doing exactly the same upload at the same time as I am not finished with the implementation. I was just curious as I thought GCS would handle concurrent writes to the same file. 

```
2016-05-20T15:16:40.301+00:00 2c9659bff0f4 build-artifact-archiver[9]: Starting to process ZIP archive [ZIP_ARCHIVE from /app/rest/builds/id:6521885/artifacts/archived/]
2016-05-20T15:16:40.666+00:00 2c9659bff0f4 build-artifact-archiver[9]: Finished processing ZIP archive [ZIP_ARCHIVE from /app/rest/builds/id:6521885/artifacts/archived/]
2016-05-20T15:16:45.015+00:00 2c9659bff0f4 build-artifact-archiver[9]: Finished processing ZIP archive [ZIP_ARCHIVE from /app/rest/builds/id:6521885/artifacts/archived/]
2016-05-20T15:16:47.780+00:00 2c9659bff0f4 build-artifact-archiver[9]: Finished processing ZIP archive [ZIP_ARCHIVE from /app/rest/builds/id:6521885/artifacts/archived/]
2016-05-20T15:16:55.045+00:00 2c9659bff0f4 build-artifact-archiver[9]: Finished processing ZIP archive [ZIP_ARCHIVE from /app/rest/builds/id:6521885/artifacts/archived/]
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: Message handler threw exception
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	com.google.cloud.storage.StorageException: insufficient data written
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.google.cloud.storage.spi.DefaultStorageRpc.translate(DefaultStorageRpc.java:98)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.google.cloud.storage.spi.DefaultStorageRpc.write(DefaultStorageRpc.java:528)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.google.cloud.storage.BlobWriteChannel$1.run(BlobWriteChannel.java:49)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.google.cloud.RetryHelper.doRetry(RetryHelper.java:181)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:247)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:237)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.google.cloud.storage.BlobWriteChannel.flushBuffer(BlobWriteChannel.java:46)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.google.cloud.BaseWriteChannel.flush(BaseWriteChannel.java:110)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.google.cloud.BaseWriteChannel.write(BaseWriteChannel.java:137)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.spotify.buildartifactarchiver.storage.GcsUploaderClient.storeInputStream(GcsUploaderClient.java:80)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.spotify.buildartifactarchiver.storage.ArtifactUploader.uploadZipArchive(ArtifactUploader.java:85)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.spotify.buildartifactarchiver.storage.ArtifactUploader.upload(ArtifactUploader.java:58)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.spotify.buildartifactarchiver.ArtifactArchiver.archiveArtifactsForBuild(ArtifactArchiver.java:90)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.spotify.buildartifactarchiver.web.ArtifactArchiverPubSubResource.messageHandler(ArtifactArchiverPubSubResource.java:116)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.spotify.google.cloud.pubsub.client.Puller.lambda$pullBatch$11(Puller.java:165)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.spotify.google.cloud.pubsub.client.PubsubFuture.succeed(PubsubFuture.java:287)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.spotify.google.cloud.pubsub.client.PubsubFuture.lambda$wrap$9(PubsubFuture.java:280)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.spotify.google.cloud.pubsub.client.PubsubFuture.succeed(PubsubFuture.java:287)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.spotify.google.cloud.pubsub.client.Pubsub.lambda$requestJavaNet$8(Pubsub.java:908)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at java.lang.Thread.run(Thread.java:745)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	Caused by: java.io.IOException: insufficient data written
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.close(HttpURLConnection.java:3500)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:81)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.google.cloud.storage.spi.DefaultStorageRpc.write(DefaultStorageRpc.java:510)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.google.cloud.storage.BlobWriteChannel$1.run(BlobWriteChannel.java:49)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.google.cloud.RetryHelper.doRetry(RetryHelper.java:181)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:247)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:237)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.google.cloud.storage.BlobWriteChannel.flushBuffer(BlobWriteChannel.java:46)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.google.cloud.BaseWriteChannel.flush(BaseWriteChannel.java:110)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.google.cloud.BaseWriteChannel.write(BaseWriteChannel.java:137)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.spotify.buildartifactarchiver.storage.GcsUploaderClient.storeInputStream(GcsUploaderClient.java:80)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.spotify.buildartifactarchiver.storage.ArtifactUploader.uploadZipArchive(ArtifactUploader.java:85)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.spotify.buildartifactarchiver.storage.ArtifactUploader.upload(ArtifactUploader.java:58)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.spotify.buildartifactarchiver.ArtifactArchiver.archiveArtifactsForBuild(ArtifactArchiver.java:90)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.spotify.buildartifactarchiver.web.ArtifactArchiverPubSubResource.messageHandler(ArtifactArchiverPubSubResource.java:116)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.spotify.google.cloud.pubsub.client.Puller.lambda$pullBatch$11(Puller.java:165)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.spotify.google.cloud.pubsub.client.PubsubFuture.succeed(PubsubFuture.java:287)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.spotify.google.cloud.pubsub.client.PubsubFuture.lambda$wrap$9(PubsubFuture.java:280)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.spotify.google.cloud.pubsub.client.PubsubFuture.succeed(PubsubFuture.java:287)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at com.spotify.google.cloud.pubsub.client.Pubsub.lambda$requestJavaNet$8(Pubsub.java:908)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2016-05-20T15:17:02.031+00:00 2c9659bff0f4 build-artifact-archiver[9]: 	at java.lang.Thread.run(Thread.java:745)
2016-05-20T15:17:03.696+00:00 2c9659bff0f4 build-artifact-archiver[9]: Finished processing ZIP archive [ZIP_ARCHIVE from /app/rest/builds/id:6521885/artifacts/archived/]
2016-05-20T15:17:09.458+00:00 2c9659bff0f4 build-artifact-archiver[9]: Finished processing ZIP archive [ZIP_ARCHIVE from /app/rest/builds/id:6521885/artifacts/archived/]
2016-05-20T15:17:27.148+00:00 2c9659bff0f4 build-artifact-archiver[9]: Finished processing ZIP archive [ZIP_ARCHIVE from /app/rest/builds/id:6521885/artifacts/archived/]
2016-05-20T15:17:31.408+00:00 2c9659bff0f4 build-artifact-archiver[9]: Finished processing ZIP archive [ZIP_ARCHIVE from /app/rest/builds/id:6521885/artifacts/archived/]
```

**Comment by mziccard** [comment] 2016-05-23 11:23
@fonzy2013 I doubt this problem is related to concurrent uploads. I have been doing some research and it seems that this is a recurrent issue, not necessarily related to `gcloud-java`:

- https://github.com/google/google-api-java-client/issues/781
- https://github.com/pinterest/secor/issues/177
- http://stackoverflow.com/questions/36230837/google-cloud-storage-multipart-upload-exception-insufficient-data-written
- http://stackoverflow.com/questions/11480578/ioexception-when-insert-file-to-google-drive/30796105#30796105

However, I have been uploading different size files since this morning (using your code) and I couldn't manage to reproduce the error. Are these errors recurring on the same file/file size or completely spurious? Information on the size (or size range) of files you are trying to upload might help as well.

**Comment by volgin** [comment] 2016-06-05 06:13
I get this exception every few hours over the past 24 hours, while I have not seen it before. Hundreds of files load fine, and then all of a sudden this exception happens. When I restart my program, the same file that threw this exception loads with no problems.

Here is the trace:
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: com.google.cloud.storage.StorageException: insufficient data written
	at com.google.cloud.storage.spi.DefaultStorageRpc.translate(DefaultStorageRpc.java:98)
	at com.google.cloud.storage.spi.DefaultStorageRpc.write(DefaultStorageRpc.java:528)
	at com.google.cloud.storage.BlobWriteChannel$1.run(BlobWriteChannel.java:49)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at com.google.cloud.RetryHelper.doRetry(RetryHelper.java:181)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:247)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:237)
	at com.google.cloud.storage.BlobWriteChannel.flushBuffer(BlobWriteChannel.java:46)
	at com.google.cloud.BaseWriteChannel.close(BaseWriteChannel.java:149)
	at com.rebelation.ingest.server.IngestServer.uploadFile(IngestServer.java:484)
	at com.rebelation.ingest.server.IngestServer.moveFile(IngestServer.java:450)
	at com.rebelation.ingest.server.IngestServer.processFile(IngestServer.java:404)
	at com.rebelation.ingest.server.IngestServer.processFileOrDirectory(IngestServer.java:194)
	at com.rebelation.ingest.server.IngestServer.processFileOrDirectory(IngestServer.java:187)
	at com.rebelation.ingest.server.IngestServer.processFileOrDirectory(IngestServer.java:187)
	at com.rebelation.ingest.server.IngestServer.processFileOrDirectory(IngestServer.java:187)
	at com.rebelation.ingest.server.IngestServer.processType(IngestServer.java:179)
	at com.rebelation.ingest.server.IngestServer.startLoop(IngestServer.java:147)
	at com.rebelation.ingest.server.IngestServer.main(IngestServer.java:122)
	... 5 more
Caused by: java.io.IOException: insufficient data written
	at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.close(HttpURLConnection.java:3227)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:81)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:972)
	at com.google.cloud.storage.spi.DefaultStorageRpc.write(DefaultStorageRpc.java:510)
	... 22 more

**Comment by mziccard** [comment] 2016-06-06 08:36
I am trying to get to the bottom of this but I haven't been able to reproduce the error yet. Where are your applications running?

Do you have any change of trying out the changes in [this branch](https://github.com/mziccard/gcloud-java/tree/storage-insufficient-data) and let me know if you still get those errors?

**Comment by volgin** [comment] 2016-06-06 18:49
I process ~500,000 files using a mix of Mac OS and Windows 10 PCs. I saw error this error on all of them. The error appears to be random - sometimes hundreds, sometimes thousands of files upload without problems before this exception occurs. This may explain why you cannot reproduce this error when trying with just a few files.

I attached a couple of files that failed to upload. Both files succeeded on a second attempt, though.

I have switched from
`writer.write(ByteBuffer.wrap(buffer, 0, limit));`
 to
`storage.create(blobInfo, Files.readAllBytes(file.toPath()));`
for the now, and I have not seen this error. But again, maybe a few thousand files later :)

[Archive.zip](https://github.com/GoogleCloudPlatform/gcloud-java/files/301082/Archive.zip)

**Comment by mziccard** [comment] 2016-06-06 19:34
> I have switched from
writer.write(ByteBuffer.wrap(buffer, 0, limit));
to
storage.create(blobInfo, Files.readAllBytes(file.toPath()));

That might work (it's in line with the workarounds of this issue I found around the internet) but it uses direct upload. Writer should be favored for large files.

Thanks for sharing the files, I'll create a more "stressing" test. Any change you can build  an artifact from the code in [this repository](https://github.com/mziccard/gcloud-java/tree/storage-insufficient-data) and run your application with that?

**Comment by fonzy2013** [comment] 2016-08-15 14:26
Any chance someone looked further into this? I have large files that needs to be uploaded so uploading them using storage.create(BlobInfo, byte[]) doesn't work.
Is there anything I can do to help with this?

**Comment by mziccard** [comment] 2016-08-15 15:01
Hi @fonzy2013, it would be really helpful if you could build gcloud-java from the code at https://github.com/mziccard/gcloud-java/tree/storage-insufficient-data and give it a try. If you need me to I can rebase that code on top of master (to catch latest changes).

**Comment by fonzy2013** [comment] 2016-08-16 11:28
@mziccard, I gave it a try and I can't see that exception now. However I will report 2 other ones in another thread that I have seen lately (SocketException: Operation timed out and SocketException: Socket is closed).

I saw this fix was to implement a retry, do you know how the underlying problem can be adressed?

**Comment by mziccard** [comment] 2016-08-16 11:54
> I saw this fix was to implement a retry, do you know how the underlying problem can be adressed?

I already reported here all information that I have on this issue. This is not an issue with `gcloud-java` but with [google-api-java-client](https://github.com/google/google-api-java-client/issues/781) that seems to have remained opened for a while. There not much that we can do at our layer other than retrying the exception.

> However I will report 2 other ones in another thread that I have seen lately (SocketException: Operation timed out and SocketException: Socket is closed).

Out of curiosity, where is you application running? You should be able to mitigate these exceptions by setting more permissive read and connect timeouts (by using `connectTimeout(int connectTimeout)` and `readTimeout(int readTimeout)` in `StorageOptions.Builder`.

**Comment by fonzy2013** [comment] 2016-08-17 08:08
Our application is running on our own servers. 
Here are some details about the hosts:

```
root@9f4896ab558e:/# /usr/bin/java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

root@9f4896ab558e:/# uname -a
Linux 9f4896ab558e 3.16.0-41-generic #57~14.04.1-Ubuntu SMP Thu Jun 18 18:01:13 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

No specific jvm options
```

**Comment by mziccard** [comment] 2016-08-23 17:25
In #1187 we added this exception to our retry logic. This should mitigate the issue.

I am closing this but feel free to reopen if you still experience the exception.

**Closed by mziccard** 2016-08-23 17:25 UTC
