### ISSUE TITLE
makeClient INFO: Not using any credentials

### ISSUE THREAD

**Issue by unitydynamics** [GoogleCloudPlatform/gcloud-java#872] opened 2016-04-07 17:19 UTC
Well I was hoping that this would completely go away with 0.1.7... but I see this has been changed from a WARNING to an INFO.  I don't need credentials because of my setup.  Despite that, this is in my logs *for every single call* to the datastore.  Thousands of times.  Makes my logs much harder to read.  Is there a "quiet" option?  If not I'd like to formally request one.  This is spit out on stderr.

**Comment by ajkannan** [comment] 2016-04-07 20:09
I think we can detect and avoid writing that particular log by checking for it in [this logic](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/gcloud-java-datastore/src/main/java/com/google/gcloud/datastore/testing/LocalGcdHelper.java#L269).  Do you agree @aozarov?

**Comment by ajkannan** [comment] 2016-04-07 21:16
Update: I actually misinterpreted the issue in my first response.  The issue is with the Cloud Datastore's client, which gcloud-java depend on.  I've created a pull request to remove that log (see [here](https://github.com/GoogleCloudPlatform/google-cloud-datastore/pull/104)).  After that change is released by the Datastore folks and gcloud-java releases it's next version, this should be fixed.

**Comment by mziccard** [comment] 2016-05-18 13:04
This is fixed now

**Closed by mziccard** 2016-05-18 13:04 UTC
Labels: datastore
